/**
 * This class is generated by jOOQ
 */
package com.gooru.beans.jooq.public_.tables.records;


import com.gooru.beans.jooq.public_.tables.GooruUser;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GooruUserRecord extends UpdatableRecordImpl<GooruUserRecord> implements Record4<Integer, String, Object, String> {

	private static final long serialVersionUID = 878736043;

	/**
	 * Setter for <code>public.gooru_user.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.gooru_user.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.gooru_user.user_name</code>.
	 */
	public void setUserName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.gooru_user.user_name</code>.
	 */
	public String getUserName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.gooru_user.attributes</code>.
	 */
	public void setAttributes(Object value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.gooru_user.attributes</code>.
	 */
	public Object getAttributes() {
		return (Object) getValue(2);
	}

	/**
	 * Setter for <code>public.gooru_user.attributes_text</code>.
	 */
	public void setAttributesText(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.gooru_user.attributes_text</code>.
	 */
	public String getAttributesText() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Object, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, Object, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return GooruUser.GOORU_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return GooruUser.GOORU_USER.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field3() {
		return GooruUser.GOORU_USER.ATTRIBUTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return GooruUser.GOORU_USER.ATTRIBUTES_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value3() {
		return getAttributes();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAttributesText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GooruUserRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GooruUserRecord value2(String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GooruUserRecord value3(Object value) {
		setAttributes(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GooruUserRecord value4(String value) {
		setAttributesText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GooruUserRecord values(Integer value1, String value2, Object value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GooruUserRecord
	 */
	public GooruUserRecord() {
		super(GooruUser.GOORU_USER);
	}

	/**
	 * Create a detached, initialised GooruUserRecord
	 */
	public GooruUserRecord(Integer id, String userName, Object attributes, String attributesText) {
		super(GooruUser.GOORU_USER);

		setValue(0, id);
		setValue(1, userName);
		setValue(2, attributes);
		setValue(3, attributesText);
	}
}
