/**
 * This class is generated by jOOQ
 */
package com.gooru.beans.jooq.public_;


import com.gooru.beans.jooq.public_.tables.GooruUser;
import com.gooru.beans.jooq.public_.tables.records.GooruUserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<GooruUserRecord, Integer> IDENTITY_GOORU_USER = Identities0.IDENTITY_GOORU_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<GooruUserRecord> GOORU_USER_PKEY = UniqueKeys0.GOORU_USER_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<GooruUserRecord, Integer> IDENTITY_GOORU_USER = createIdentity(GooruUser.GOORU_USER, GooruUser.GOORU_USER.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<GooruUserRecord> GOORU_USER_PKEY = createUniqueKey(GooruUser.GOORU_USER, GooruUser.GOORU_USER.ID);
	}
}
