/**
 * This class is generated by jOOQ
 */
package com.gooru.beans.jooq.public_;


import com.gooru.beans.jooq.public_.tables.GooruUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.gooru_user
	 */
	public static final GooruUser GOORU_USER = com.gooru.beans.jooq.public_.tables.GooruUser.GOORU_USER;
}
